### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Kaylaesmith1** [Kaylaesmith1/budget_busters#15]

**Comment by DeeMcCart** [comment]
Site features(first draft):
**F01 Site purpose is clearly identified and apparent a user who reaches the site**
(Future.  as in the very near future before we submit)
Information is organised logically, with goal-setting, spend tracking, budget monitoring and insight analysis.
There is an infomative 'About' page and an opportunity for the user to provide feedback, suggestions for future development, or issues withthe site. 
<screenprints to folllow>
<landing page>
<navbar>

This satisfies user required FTU01 - clear site purpose in order to decide to proceed.

** F02 Ease of navigation**
The overall site layout follows a show-hide system, so relevant sections of the site are visible to the user.
A navgation bar gives ease of movement between the various site functions.  

At the bottom of each section there is a 'minimise' arrow to hide the relevant section and return to the navbar options.
This satisfies user requirements FTU02, FTU03, allowing the user, whether first-time or returning user to navigate smoothly within the site. 

** F03 Responsivess **
The site was constructed on a mobile-first principle.   Each section has been constructed to be responsive to the screen size of the device it is run on.   
<am-i-responsive- screenprint>

Responsive design principles such as using on-sceen buttons, pre-filled prompts and pop-ups rather than text-based entry,  make the site good for small-screen usage.
<screenprint(s) of spending entry panel>

This satisfies first-time user requirements FTU05

** F04 Accessibility and Performance **
The site performs well and satisfies accessibiliyt guidenlines (CHECK)
<screenprint of lighthouse performance>
<screenprint of W3C accessibility checker>

** F05  
F06
F07
F08
F09
F10

**Comment by CaylinDewey** [comment]
Please let me know when the screen shots can be taken so that I can build this with the text above in the readme file.
